# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spectrum_Details' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSONModel'
  # Pods for Spectrum_Details

  target 'Spectrum_DetailsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Spectrum_DetailsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
